#!/usr/bin/env python3
"""
D03 fixture scan tool — bounded, READ-ONLY evidence generation for the NSE 10Y
historical archive investigation (gate D03). This is EVIDENCE TOOLING, not part
of any engine; it implements no ingestion, no persistence, no schema.

Fixtures (generated by running this on the Windows archive environment):
  FIX-SEM-DEF-01        metric-definition reconstruction for D01 isin_count/symbol_count
  FIX-UD-CENSUS-01      full UDiFF census grouped by (Sgmt, Src, FinInstrmTp, SctySrs)
  FIX-UD-ROW-SAMPLE-01  stratified bounded row samples across BOTH formats (Legacy+UDiFF)
  FIX-LEG-CENSUS-01     full Legacy identity census (blank/invalid ISINs, RE-prefix evidence)
  FIX-XCONT-01          cross-format continuity at 2024-07-05 <-> 2024-07-08 (ISIN primary,
                        (SYMBOL,SERIES) secondary — not identity)
  FIX-SYMBOL-HIST-01    effective-dated symbol/series ledger (aggregates + transitions only)
  FIX-SERIES-EVENTS-01  series transition & same-day co-occurrence census (ST anomaly test)
  FIX-OVERLAY-SEM-01    overlay (BL/T0/BO/IT/IL) vs same-day base-row semantics
  FIX-ANOM-01           raw inspection of 2017-07-10 / 2020-07-13 + window neighbours

Guarantees:
  * READ-ONLY on archives (open for reading only; never written/renamed/moved).
  * Deterministic: documented fixed selection rules, explicit sort keys with
    deterministic secondary tie-breakers, no RNG use. Payload files are
    byte-identical across runs when --frozen-time is fixed.
  * MANIFEST.sha256 covers every payload file; RUN_INFO.json holds provenance
    (tool sha256, roots, counts, selection criteria, timestamp).
  * The UDiFF 34-field header width is VERIFIED from files, not assumed.

Assumption (checked and reported per file): if a CSV's logical row count equals
its physical line count, verbatim raw samples are emitted; otherwise rows are
re-serialized with the csv module (still deterministic) and flagged.

Python 3.8+, stdlib only.
"""

import argparse
import csv
import datetime as _dt
import hashlib
import io
import json
import os
import re
import sys
import zipfile
from dataclasses import dataclass
from collections import defaultdict

TOOL_VERSION = "d03-fixture-scan-1.1.0"

UDIFF_NAME_RE = re.compile(
    r"^BhavCopy_NSE_CM_(\d)_(\d)_(\d)_(\d{4})(\d{2})(\d{2})_([A-Z])_(\d{4})\.csv\.zip$")
MONTHS = {m: i for i, m in enumerate(
    ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"], start=1)}

OVERLAY_SERIES = frozenset({"BL", "BO", "T0", "IT", "IL"})     # candidate overlay classes (D02)
FOCUS_SERIES = ("ST", "BE", "BZ", "EQ", "SM", "SZ")            # D03 §9 focus set
ETF_TICKER_HINTS = ("BEES", "ETF")                             # evidence-only heuristic, NOT classification
UDIFF_HEADER_FIELDS = 34
LEGACY_HEADER_FIELDS = 13

SEMDEF_TARGETS = [("LEGACY", "2016-09-20"), ("LEGACY", "2018-06-01"), ("LEGACY", "2020-07-13"),
                  ("LEGACY", "2021-07-01"), ("LEGACY", "2022-10-03"), ("LEGACY", "2023-06-01"),
                  ("LEGACY", "2024-07-05"), ("UDIFF", "2024-07-08")]
ROW_SAMPLE_UDIFF = ["2024-07-08", "2025-10-30", "2026-08-25"]
ROW_SAMPLE_LEGACY = ["2016-09-20", "2022-10-03", "2024-03-28", "2024-07-05"]
ANOM_TARGETS = ["2017-07-10", "2020-07-13"]


# ---------------------------------------------------------------- primitives
def sha256_file(path, chunk=1 << 20):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(chunk), b""):
            h.update(b)
    return h.hexdigest()


def norm(s):
    return (s or "").strip().upper()


def isin_check_digit(body11):
    vals = []
    for ch in body11.upper():
        if ch.isdigit():
            vals.append(ch)
        elif "A" <= ch <= "Z":
            vals.append(str(ord(ch) - 55))
        else:
            return None
    digits, total, dbl = "".join(vals), 0, True
    for ch in reversed(digits):
        d = int(ch)
        if dbl:
            d *= 2
            if d > 9:
                d -= 9
        total += d
        dbl = not dbl
    return (10 - total % 10) % 10


def make_isin(body11):
    return body11 + str(isin_check_digit(body11))


def validate_isin(s):
    """-> category ∈ {BLANK, VALID, INVALID_LEN, INVALID_PREFIX, INVALID_CHARSET, INVALID_CHECKDIGIT}"""
    v = norm(s).replace(" ", "")
    if v == "":
        return "BLANK"
    if len(v) != 12:
        return "INVALID_LEN"
    if not v.startswith("IN"):
        return "INVALID_PREFIX"
    if not re.fullmatch(r"IN[A-Z0-9]{9}[0-9]", v):
        return "INVALID_CHARSET"
    return "VALID" if isin_check_digit(v[1:11]) == int(v[11]) else "INVALID_CHECKDIGIT"


def read_zip_text(zip_path):
    with zipfile.ZipFile(zip_path) as zf:
        data = zf.read(zf.namelist()[0])
    return data.decode("utf-8-sig", errors="replace")


def iter_rows(zip_path):
    """Yield (row_index, fields). row_index 0 = header."""
    for i, r in enumerate(csv.reader(io.StringIO(read_zip_text(zip_path)))):
        yield i, r


def header_index(zip_path):
    for i, r in iter_rows(zip_path):
        names = [h.strip() for h in r]
        return names, {n: j for j, n in enumerate(names) if n}
    raise ValueError("empty archive: " + zip_path)


def get(r, idx, col):
    j = idx.get(col)
    return r[j] if j is not None and j < len(r) else ""


def is_udiff_header(names):
    return "TckrSymb" in names and "SctySrs" in names


@dataclass
class Archive:
    kind: str
    path: str
    name: str
    date: str

    def key(self):
        return (self.date, self.kind, self.name)


def discover(legacy_root, udiff_root):
    out = []
    for kind, root in (("LEGACY", legacy_root), ("UDIFF", udiff_root)):
        if not root or not os.path.isdir(root):
            continue
        for dirpath, _dirs, names in os.walk(root):
            for nm in names:
                d = None
                if kind == "LEGACY":
                    m = re.fullmatch(r"cm(\d{2})([A-Z]{3})(\d{4})bhav\.csv\.zip", nm)
                    if m and m.group(2) in MONTHS:
                        d = "%s-%02d-%02d" % (m.group(3), MONTHS[m.group(2)], int(m.group(1)))
                else:
                    m = UDIFF_NAME_RE.match(nm)
                    if m:
                        d = "%s-%s-%s" % (m.group(4), m.group(5), m.group(6))
                if d:
                    a = Archive(kind, os.path.join(dirpath, nm), nm, d)
                    out.append(a)
    out.sort(key=Archive.key)
    return out


def select_file(files, kind, target_date):
    """exact date, else earliest on/after target; deterministic."""
    exact = [f for f in files if f.kind == kind and f.date == target_date]
    if exact:
        return exact[0], "exact"
    after = sorted((f for f in files if f.kind == kind and f.date >= target_date), key=Archive.key)
    return (after[0], "next_on_after") if after else (None, "not_found")


class Writer:
    def __init__(self, outdir):
        self.outdir = outdir
        os.makedirs(outdir, exist_ok=True)
        self.payloads = []

    def csv(self, fixture, name, header, rows):
        p = os.path.join(self.outdir, fixture + "__" + name)
        with open(p, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, lineterminator="\n")
            if header is not None:
                w.writerow(header)
            w.writerows(rows)
        self.payloads.append(p)

    def raw(self, fixture, name, lines):
        p = os.path.join(self.outdir, fixture + "__" + name)
        with open(p, "w", newline="\n", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
        self.payloads.append(p)

    def json(self, fixture, name, obj):
        p = os.path.join(self.outdir, fixture + "__" + name)
        with open(p, "w", encoding="utf-8") as f:
            json.dump(obj, f, indent=2, sort_keys=True)
            f.write("\n")
        self.payloads.append(p)


# ---------------------------------------------------------------- FIX-SEM-DEF-01
def file_metrics(zip_path):
    names, idx = header_index(zip_path)
    ud = is_udiff_header(names)
    sym_c = idx.get("TckrSymb" if ud else "SYMBOL")
    ser_c = idx.get("SctySrs" if ud else "SERIES")
    isin_c = idx.get("ISIN")
    rows = blank_isin = nonblank_isin_rows = blank_sym = 0
    isin_set, sym_set, pair_set = set(), set(), set()
    pair_count = defaultdict(int)
    for i, r in iter_rows(zip_path):
        if i == 0:
            continue
        rows += 1
        sym = norm(get(r, idx, "TckrSymb" if ud else "SYMBOL"))
        ser = norm(get(r, idx, "SctySrs" if ud else "SERIES"))
        isin = norm(get(r, idx, "ISIN"))
        if isin == "":
            blank_isin += 1
        else:
            nonblank_isin_rows += 1
            isin_set.add(isin)
        if sym == "":
            blank_sym += 1
        else:
            sym_set.add(sym)
        pair_set.add((sym, ser))
        pair_count[(sym, ser)] += 1
    pair_dupes = sum(c - 1 for c in pair_count.values() if c > 1)
    return {
        "file": os.path.basename(zip_path), "format": "UDIFF" if ud else "LEGACY",
        "rows": rows,
        "blank_isin_rows": blank_isin,
        "distinct_nonblank_isin": len(isin_set),
        "nonblank_isin_rows": nonblank_isin_rows,
        "isins_extra_duplicate_rows": nonblank_isin_rows - len(isin_set),
        "blank_symbol_rows": blank_sym,
        "distinct_nonblank_symbol": len(sym_set),
        "distinct_symbol_series_pairs": len(pair_set),
        "symbol_series_duplicate_rows": pair_dupes,
    }


def fx_semdef(files, w, args):
    """Full-corpus per-file metric reconstruction on competing definitions, joined
    to the D01 inventory so D01's exact semantics are determined (not assumed).
    Selected D02 target dates are additionally flagged for presentation."""
    target_files = {}
    for kind, target in SEMDEF_TARGETS:
        a, sel = select_file(files, kind, target)
        if a is not None:
            target_files[a.name] = (target, sel)
    rows = []
    for a in sorted(files, key=lambda x: x.key()):
        m = file_metrics(a.path)
        m["is_d02_target"] = a.name in target_files
        m["requested_date"] = target_files[a.name][0] if a.name in target_files else ""
        m["selection"] = target_files[a.name][1] if a.name in target_files else ""
        if args.d01_inventory and os.path.isfile(args.d01_inventory):
            d01 = lookup_d01(args.d01_inventory, m["file"])
            if d01:
                m["d01_isin_count"] = d01["isin_count"]
                m["d01_symbol_count"] = d01["symbol_count"]
                m["d01_isin_eq_distinct_nonblank"] = (d01["isin_count"] == m["distinct_nonblank_isin"])
                m["d01_isin_eq_nonblank_rows"] = (d01["isin_count"] == m["nonblank_isin_rows"])
                m["d01_sym_eq_distinct_nonblank"] = (d01["symbol_count"] == m["distinct_nonblank_symbol"])
                m["d01_sym_eq_rows"] = (d01["symbol_count"] == m["rows"])
                m["discriminating_file"] = (m["isins_extra_duplicate_rows"] > 0) or (m["blank_isin_rows"] > 0)
        rows.append(m)
    keys = ["format", "date", "file", "header_fields", "rows", "blank_symbol_rows",
            "blank_isin_rows", "nonblank_isin_rows", "distinct_nonblank_isin",
            "isins_extra_duplicate_rows", "distinct_nonblank_symbol",
            "distinct_symbol_series_pairs", "symbol_series_duplicate_rows",
            "is_d02_target", "requested_date", "selection",
            "d01_isin_count", "d01_symbol_count",
            "d01_isin_eq_distinct_nonblank", "d01_isin_eq_nonblank_rows",
            "d01_sym_eq_distinct_nonblank", "d01_sym_eq_rows", "discriminating_file"]
    keys = [k for k in keys if any(k in r for r in rows)]
    w.csv("FIX-SEM-DEF-01", "metrics.csv", keys, [[r.get(k, "") for k in keys] for r in rows])
    discriminating = [r for r in rows if r.get("discriminating_file") and "d01_isin_count" in r]
    n_dist = sum(1 for r in discriminating if r.get("d01_isin_eq_distinct_nonblank"))
    n_rows = sum(1 for r in discriminating if r.get("d01_isin_eq_nonblank_rows"))
    verdict = ("D01 isin_count == DISTINCT-NONBLANK" if (discriminating and n_dist == len(discriminating) and n_rows != n_dist)
               else "D01 isin_count == NONBLANK-ROWS" if (discriminating and n_rows == len(discriminating) and n_rows != n_dist)
               else "AMBIGUOUS/MIXED - see per-file flags" if discriminating
               else "NO DISCRIMINATING FILES AVAILABLE")
    w.json("FIX-SEM-DEF-01", "d01_definition_verdict.json", {
        "discriminating_files": len(discriminating),
        "match_distinct_nonblank": n_dist,
        "match_nonblank_rows": n_rows,
        "verdict": verdict,
        "note": "Verdict derived only from files where the two definitions differ; non-discriminating files cannot distinguish them.",
    })
    w.json("FIX-SEM-DEF-01", "formula_definitions.json", {
        "formulas": {
            "rows": "count of data rows (header excluded)",
            "blank_isin_rows": "rows where ISIN is empty/whitespace-only",
            "distinct_nonblank_isin": "count of unique ISIN values (whitespace-stripped, uppercased, non-blank)",
            "nonblank_isin_rows": "count of rows with non-blank ISIN (duplicates included)",
            "isins_extra_duplicate_rows": "nonblank_isin_rows minus distinct_nonblank_isin",
            "distinct_nonblank_symbol": "count of unique non-blank symbols (stripped, uppercased)",
            "distinct_symbol_series_pairs": "count of unique (symbol,series) pairs",
            "symbol_series_duplicate_rows": "sum over pairs of (occurrences - 1)",
        },
        "reconstruction_rule": ("D01 isin_count is DISTINCT-NONBLANK iff, on a discriminating file "
                                "(duplicates or blanks present), d01_isin_count == distinct_nonblank_isin; "
                                "it is NONBLANK-ROWS iff == nonblank_isin_rows."),
        "note": "No D01 evidence is altered. This fixture only reconstructs and documents definitions.",
    })
    return rows


_D01_CACHE = {}


def lookup_d01(inv_path, file_name):
    if inv_path not in _D01_CACHE:
        with open(inv_path) as f:
            _D01_CACHE[inv_path] = {e["file_name"]: e for e in json.load(f)}
    return _D01_CACHE[inv_path].get(file_name)


# ---------------------------------------------------------------- FIX-UD-CENSUS-01
def fx_ud_census(files, w, args):
    udfs = [a for a in files if a.kind == "UDIFF"]
    groups = defaultdict(lambda: {"files": set(), "rows": 0, "blank_isin": 0, "isins": set(),
                                 "blank_fid": 0, "fids": set(), "fid_eq": 0, "fid_ne": 0,
                                 "blank_tk": 0, "tks": set(), "first": "9999-99-99", "last": "0000-00-00"})
    marg = {c: defaultdict(lambda: {"rows": 0, "files": set()}) for c in ("Sgmt", "Src", "FinInstrmTp", "SctySrs")}
    widths = defaultdict(int)
    sigs = defaultdict(int)
    for a in udfs:
        names, idx = header_index(a.path)
        widths[len(names)] += 1
        sigs[",".join(names)] += 1
        for i, r in iter_rows(a.path):
            if i == 0:
                continue
            sgmt, src, ftyp, srs = (get(r, idx, "Sgmt").strip(), get(r, idx, "Src").strip(),
                                     get(r, idx, "FinInstrmTp").strip(), norm(get(r, idx, "SctySrs")))
            key = (sgmt, src, ftyp, srs)
            g = groups[key]
            g["files"].add(a.name)
            g["rows"] += 1
            g["first"], g["last"] = min(g["first"], a.date), max(g["last"], a.date)
            isin, fid, tk = norm(get(r, idx, "ISIN")), norm(get(r, idx, "FinInstrmId")), norm(get(r, idx, "TckrSymb"))
            if isin == "":
                g["blank_isin"] += 1
            else:
                g["isins"].add(isin)
            if fid == "":
                g["blank_fid"] += 1
            else:
                g["fids"].add(fid)
            if fid and isin:
                g["fid_eq" if fid == isin else "fid_ne"] += 1
            if tk == "":
                g["blank_tk"] += 1
            else:
                g["tks"].add(tk)
            for colname, val in (("Sgmt", sgmt), ("Src", src), ("FinInstrmTp", ftyp), ("SctySrs", srs)):
                marg[colname][val]["rows"] += 1
                marg[colname][val]["files"].add(a.name)
    out = []
    for (sgmt, src, ftyp, srs), g in sorted(groups.items()):
        out.append([sgmt, src, ftyp, srs, len(g["files"]), g["rows"], len(g["isins"]), g["blank_isin"],
                    len(g["fids"]), g["blank_fid"], len(g["tks"]), g["blank_tk"], g["fid_eq"], g["fid_ne"],
                    g["first"], g["last"]])
    w.csv("FIX-UD-CENSUS-01", "groups.csv",
          ["Sgmt", "Src", "FinInstrmTp", "SctySrs", "archive_count", "row_count",
           "distinct_nonblank_isin", "blank_or_ws_isin_rows", "distinct_nonblank_finstrmid",
           "blank_or_ws_finstrmid_rows", "distinct_nonblank_tckrsymb", "blank_or_ws_tckrsymb_rows",
           "finstrmid_eq_isin_rows", "finstrmid_ne_isin_rows", "first_date", "last_date"], out)
    for colname in ("Sgmt", "Src", "FinInstrmTp", "SctySrs"):
        w.csv("FIX-UD-CENSUS-01", "marginal_%s.csv" % colname.lower(), [colname, "row_count", "archive_count"],
              [[v, m["rows"], len(m["files"])] for v, m in sorted(marg[colname].items())])
    w.json("FIX-UD-CENSUS-01", "header_width_check.json", {
        "expected_fields": UDIFF_HEADER_FIELDS,
        "observed_width_counts": {str(k): v for k, v in sorted(widths.items())},
        "distinct_header_signatures": len(sigs),
        "files_scanned": len(udfs),
        "verdict": ("VERIFIED: every UDiFF file has exactly the expected header width"
                    if set(widths) == {UDIFF_HEADER_FIELDS} else "MISMATCH — inspect header signatures"),
        "header_signatures": sorted(sigs),
    })


# ---------------------------------------------------------------- FIX-UD-ROW-SAMPLE-01
def sample_file(zip_path, per_class_cap, special_cap):
    names, idx = header_index(zip_path)
    ser_c = idx.get("SctySrs", idx.get("SERIES"))
    sym_c = idx.get("TckrSymb", idx.get("SYMBOL"))
    isin_c = idx.get("ISIN")
    fid_c = idx.get("FinInstrmId")
    ud = is_udiff_header(names)
    text = read_zip_text(zip_path)
    physical = text.split("\n")
    all_rows = list(csv.reader(io.StringIO(text)))
    line_aligned = sum(1 for p in physical if p != "") == len(all_rows)
    counts = defaultdict(int)
    chosen, specials = [], []
    for i in range(1, len(all_rows)):
        r = all_rows[i]
        ser = norm(r[ser_c]) if ser_c is not None and ser_c < len(r) else ""
        sym = norm(r[sym_c]) if sym_c is not None and sym_c < len(r) else ""
        isin = norm(r[isin_c]) if isin_c is not None and isin_c < len(r) else ""
        fid = norm(r[fid_c]) if fid_c is not None and fid_c < len(r) else ""
        if counts[ser] < per_class_cap:
            counts[ser] += 1
            chosen.append(i)
        elif sym.startswith("RE") or any(h in sym for h in ETF_TICKER_HINTS) or (ud and isin == "") or (ud and fid == ""):
            specials.append(i)
    sel = sorted(set(chosen) | set(specials[:special_cap]))
    def emit(i):
        if line_aligned and len(physical) > i:
            return physical[i]          # verbatim original line
        return ",".join(all_rows[i])    # deterministic re-serialization (flagged)
    return {"line_aligned": line_aligned, "total_data_rows": len(all_rows) - 1,
            "header_raw": physical[0], "rows_raw": [emit(i) for i in sel]}


def coverage_of(zip_path):
    names, idx = header_index(zip_path)
    ser_c = idx.get("SctySrs", idx.get("SERIES"))
    sym_c = idx.get("TckrSymb", idx.get("SYMBOL"))
    td_c, bd_c = idx.get("TradDt"), idx.get("BizDt")
    cov = defaultdict(int)
    for i, r in iter_rows(zip_path):
        if i == 0:
            continue
        ser = norm(r[ser_c]) if ser_c is not None and ser_c < len(r) else ""
        sym = norm(r[sym_c]) if sym_c is not None and sym_c < len(r) else ""
        if ser:
            cov["SERIES:" + ser] += 1
        if sym.startswith("RE"):
            cov["SYMBOL_RE_prefix"] += 1
        if any(h in sym for h in ETF_TICKER_HINTS):
            cov["SYMBOL_ETF_hint"] += 1
        if td_c is not None and bd_c is not None and get(r, idx, "TradDt").strip() != get(r, idx, "BizDt").strip():
            cov["TRADDT_NE_BIZDT"] += 1
    return dict(sorted(cov.items()))


def fx_row_sample(files, w, args):
    ud_targets = sorted(set(ROW_SAMPLE_UDIFF))
    lg_targets = sorted(set(ROW_SAMPLE_LEGACY))
    # dynamic UDiFF targets: max-BL date and first TradDt!=BizDt date (bounded scan pass)
    bl_max, bl_max_date, biz_date = -1, None, None
    for a in [x for x in files if x.kind == "UDIFF"]:
        _n, idx = header_index(a.path)
        td_c, bd_c = idx.get("TradDt"), idx.get("BizDt")
        bl = 0
        mismatch = False
        for i, r in iter_rows(a.path):
            if i == 0:
                continue
            if norm(get(r, idx, "SctySrs")) == "BL":
                bl += 1
            if not mismatch and td_c is not None and bd_c is not None and td_c < len(r) and bd_c < len(r) \
                    and get(r, idx, "TradDt").strip() != get(r, idx, "BizDt").strip():
                mismatch = True
        if bl > bl_max:
            bl_max, bl_max_date = bl, a.date
        if mismatch and biz_date is None:
            biz_date = a.date
    if bl_max_date:
        ud_targets.append(bl_max_date)
    if biz_date:
        ud_targets.append(biz_date)
    ud_targets = sorted(set(ud_targets))
    coverage, emitted = {}, 0
    for kind, targets in (("UDIFF", ud_targets), ("LEGACY", lg_targets)):
        for t in targets:
            a, sel = select_file(files, kind, t)
            if a is None:
                coverage["%s|%s" % (kind, t)] = {"status": "FILE NOT FOUND — recorded, not manufactured"}
                continue
            s = sample_file(a.path, per_class_cap=25, special_cap=200)
            fname = "sample_%s_%s.csv" % (kind.lower(), a.date)
            w.raw("FIX-UD-ROW-SAMPLE-01", fname, [s["header_raw"]] + s["rows_raw"])
            emitted += len(s["rows_raw"])
            cov = coverage_of(a.path)
            coverage["%s|%s" % (kind, a.date)] = {
                "selection": sel, "full_file_coverage": cov, "sampled_rows": len(s["rows_raw"]),
                "total_data_rows": s["total_data_rows"], "raw_lines_verbatim": s["line_aligned"],
            }
            for req in ("ETF", "RE", "BL", "T0", "BO", "IT", "MF", "GB", "GS", "TB"):
                key = "SERIES:" + req if req not in ("ETF", "RE") else "SYMBOL_" + req + ("_hint" if req == "ETF" else "_prefix")
                if key not in cov:
                    coverage["%s|%s" % (kind, a.date)].setdefault("classes_absent_full_file", []).append(req)
            if "TRADDT_NE_BIZDT" not in cov:
                coverage["%s|%s" % (kind, a.date)].setdefault("classes_absent_full_file", []).append("TradDt!=BizDt")
        for entry in coverage.values():
            if "classes_absent_full_file" in entry:
                entry["classes_absent_note"] = "requested class not present on this date — explicitly recorded, not manufactured"
    w.json("FIX-UD-ROW-SAMPLE-01", "selection_and_coverage.json", {
        "selection_rule": ("date list fixed; per-series-class first 25 rows in file order + up to 200 special rows "
                           "(RE*/ETF-hint/blank-ISIN/blank-FinInstrmId), merged, sorted by original row index; "
                           "rows emitted verbatim (or deterministic re-serialization flagged)."),
        "udiff_dates_dynamic_added": {"max_BL": bl_max_date, "max_BL_rows": bl_max, "first_traddt_ne_bizdt": biz_date or "NONE"},
        "requested_udiff": ud_targets, "requested_legacy": lg_targets,
        "max_rows_per_date_cap": 2000, "emitted_total_rows": emitted,
        "per_date": coverage,
    })


# ---------------------------------------------------------------- FIX-LEG-CENSUS-01
def fx_leg_census(files, w, args):
    per_file, yearly = [], defaultdict(lambda: defaultdict(int))
    invalid_cats = defaultdict(int)
    for a in [x for x in files if x.kind == "LEGACY"]:
        _n, idx = header_index(a.path)
        rows = blank = valid = invalid = re_pref = re_dash = re_exact = 0
        isin_set, sym_set, pair_count = set(), set(), defaultdict(int)
        for i, r in iter_rows(a.path):
            if i == 0:
                continue
            rows += 1
            isin = norm(get(r, idx, "ISIN"))
            sym = norm(get(r, idx, "SYMBOL"))
            ser = norm(get(r, idx, "SERIES"))
            cat = validate_isin(isin)
            if cat == "BLANK":
                blank += 1
            elif cat == "VALID":
                valid += 1
                isin_set.add(isin)
            else:
                invalid += 1
                invalid_cats[cat] += 1
            if sym:
                sym_set.add(sym)
                pair_count[(sym, ser)] += 1
                if sym.startswith("RE"):
                    re_pref += 1
                    if sym.startswith("RE-") or sym.startswith("RE "):
                        re_dash += 1
                    if sym == "RE":
                        re_exact += 1
        dup_pairs = sum(c - 1 for c in pair_count.values() if c > 1)
        rec = [a.date, a.name, rows, blank, valid, invalid, len(isin_set), len(sym_set), dup_pairs,
               re_pref, re_dash, re_exact]
        per_file.append(rec)
        y = a.date[:4]
        for k, v in (("files", 1), ("rows", rows), ("blank_isin", blank), ("invalid_isin", invalid),
                     ("re_prefixed", re_pref), ("pair_dups", dup_pairs)):
            yearly[y][k] += v
    w.csv("FIX-LEG-CENSUS-01", "per_file.csv",
          ["date", "file", "rows", "blank_isin_rows", "valid_isin_rows", "invalid_isin_rows",
           "distinct_valid_isin", "distinct_symbols", "symbol_series_duplicate_rows",
           "rows_symbol_RE_prefix", "rows_symbol_RE_dash_or_space", "rows_symbol_EXACT_RE"],
          sorted(per_file))
    w.csv("FIX-LEG-CENSUS-01", "per_year.csv",
          ["year", "files", "rows", "blank_isin_rows", "invalid_isin_rows", "rows_symbol_RE_prefix",
           "symbol_series_duplicate_rows"],
          [[y] + [yearly[y][k] for k in ("files", "rows", "blank_isin", "invalid_isin", "re_prefixed", "pair_dups")]
           for y in sorted(yearly)])
    unusual = sorted((r for r in per_file if r[3] or r[5]), key=lambda r: (-max(r[3], r[5]), r[0]))[:100]
    w.csv("FIX-LEG-CENSUS-01", "unusual_files_top100.csv",
          ["date", "file", "rows", "blank_isin_rows", "valid_isin_rows", "invalid_isin_rows",
           "distinct_valid_isin", "distinct_symbols", "symbol_series_duplicate_rows",
           "rows_symbol_RE_prefix", "rows_symbol_RE_dash_or_space", "rows_symbol_EXACT_RE"], unusual)
    w.json("FIX-LEG-CENSUS-01", "summary.json", {
        "invalid_isin_categories": dict(sorted(invalid_cats.items())),
        "re_prefix_caution": ("RE-prefixed symbols are investigation evidence ONLY; rights-entitlement status "
                              "is NOT inferred from the symbol prefix alone."),
        "etf_membership": "UNRESOLVED by design — external security master not acquired (D03 scope).",
        "files_scanned": len(per_file),
    })


# ---------------------------------------------------------------- FIX-XCONT-01
def xcont_rows(a):
    _n, idx = header_index(a.path)
    ud = is_udiff_header(_n)
    out = []
    for i, r in iter_rows(a.path):
        if i == 0:
            continue
        out.append({"isin": norm(get(r, idx, "ISIN")),
                    "sym": norm(get(r, idx, "TckrSymb" if ud else "SYMBOL")),
                    "ser": norm(get(r, idx, "SctySrs" if ud else "SERIES")),
                    "close": get(r, idx, "ClsPric" if ud else "CLOSE").strip(),
                    "prevc": get(r, idx, "PrvsClsgPric" if ud else "PREVCLOSE").strip(),
                    "typ": norm(get(r, idx, "FinInstrmTp")) if ud else ""})
    return out


def fnum(s):
    try:
        return round(float(s), 2)
    except Exception:
        return None


def fx_xcont(files, w, args):
    lg, _ = select_file(files, "LEGACY", "2024-07-05")
    ud, _ = select_file(files, "UDIFF", "2024-07-08")
    if not lg or not ud:
        w.json("FIX-XCONT-01", "summary.json", {"verdict": "INSUFFICIENT EVIDENCE — boundary files missing"})
        return
    L, U = xcont_rows(lg), xcont_rows(ud)
    lset, uset = defaultdict(list), defaultdict(list)
    lpairs, upairs = defaultdict(int), defaultdict(int)
    lblank = ublank = 0
    for x in L:
        if x["isin"]:
            lset[x["isin"]].append(x)
        else:
            lblank += 1
        lpairs[(x["sym"], x["ser"])] += 1
    for x in U:
        if x["isin"]:
            uset[x["isin"]].append(x)
        else:
            ublank += 1
        upairs[(x["sym"], x["ser"])] += 1
    common = sorted(set(lset) & set(uset))
    only_l = sorted(set(lset) - set(uset))
    only_u = sorted(set(uset) - set(lset))
    sym_ch, ser_ch, chain_eq, chain_ne, chain_rows = [], [], 0, 0, []
    for isin in common:
        ls, us = lset[isin][0], uset[isin][0]
        if ls["sym"] != us["sym"]:
            sym_ch.append([isin, ls["sym"], us["sym"], ls["ser"], us["ser"]])
        if ls["ser"] != us["ser"]:
            ser_ch.append([isin, ls["ser"], us["ser"]])
        up, lc = fnum(us["prevc"]), fnum(ls["close"])
        if up is not None and lc is not None:
            if up == lc:
                chain_eq += 1
            else:
                chain_ne += 1
                if len(chain_rows) < 300:
                    chain_rows.append([isin, ls["sym"], us["sym"], ls["ser"], us["ser"], ls["close"], us["prevc"]])
    w.csv("FIX-XCONT-01", "only_legacy_isins.csv", ["isin", "symbol", "series", "close"],
          [[x, lset[x][0]["sym"], lset[x][0]["ser"], lset[x][0]["close"]] for x in only_l])
    w.csv("FIX-XCONT-01", "only_udiff_isins.csv", ["isin", "symbol", "series", "FinInstrmTp"],
          [[x, uset[x][0]["sym"], uset[x][0]["ser"], uset[x][0]["typ"]] for x in only_u])
    w.csv("FIX-XCONT-01", "matched_symbol_changes.csv",
          ["isin", "legacy_symbol", "udiff_symbol", "legacy_series", "udiff_series"], sorted(sym_ch))
    w.csv("FIX-XCONT-01", "matched_series_changes.csv", ["isin", "legacy_series", "udiff_series"], sorted(ser_ch))
    w.csv("FIX-XCONT-01", "price_chain_mismatch.csv",
          ["isin", "legacy_symbol", "udiff_symbol", "legacy_series", "udiff_series",
           "legacy_close", "udiff_prev_close"], sorted(chain_rows))
    denom = max(len(common) + len(only_l) + len(only_u), 1)
    ratio = len(common) / denom
    verdict = ("strong continuity support" if ratio > 0.99 else
               "partial continuity" if ratio > 0.95 else
               "significant unexplained discontinuity — investigate")
    w.json("FIX-XCONT-01", "summary.json", {
        "pair": {"legacy": lg.name, "udiff": ud.name},
        "legacy_rows": len(L), "udiff_rows": len(U),
        "blank_isin_rows": {"legacy": lblank, "udiff": ublank},
        "isin_matched": len(common), "isin_only_legacy": len(only_l), "isin_only_udiff": len(only_u),
        "matched_symbol_changes": len(sym_ch), "matched_series_changes": len(ser_ch),
        "price_chain_prev_close_eq_legacy_close": chain_eq,
        "price_chain_prev_close_ne_legacy_close": chain_ne,
        "secondary_symbol_series_pairs_common": len(set(lpairs) & set(upairs)),
        "secondary_key_caution": "(SYMBOL,SERIES) secondary join is NOT a durable-identity claim.",
        "match_ratio": round(ratio, 6), "mechanical_verdict": verdict,
    })


# ---------------------------------------------------------------- shared ledger
def corpus_ledger(files):
    dates = sorted({a.date for a in files})
    didx = {d: i for i, d in enumerate(dates)}
    timelines = defaultdict(list)  # isin -> (date_i, sym, ser, kind, is_overlay, row_i)
    per_file_rows = {}             # (kind,date) -> base+overlay row dicts for overlay join (memory-light per file)
    blank = defaultdict(lambda: [0, 0])
    for a in files:
        _n, idx = header_index(a.path)
        ud = is_udiff_header(_n)
        c_sym = "TckrSymb" if ud else "SYMBOL"
        c_ser = "SctySrs" if ud else "SERIES"
        names, rows = _n, []
        for i, r in iter_rows(a.path):
            if i == 0:
                continue
            rec = {"date": a.date, "row": i, "isin": norm(get(r, idx, "ISIN")),
                   "sym": norm(get(r, idx, c_sym)), "ser": norm(get(r, idx, c_ser)),
                   "qty": get(r, idx, "TtlTradgVol" if ud else "TOTTRDQTY").strip(),
                   "val": get(r, idx, "TtlTrfVal" if ud else "TOTTRDVAL").strip(),
                   "trd": get(r, idx, "TtlNbOfTxsExctd" if ud else "TOTALTRADES").strip(),
                   "close": get(r, idx, "ClsPric" if ud else "CLOSE").strip()}
            rows.append(rec)
            if rec["isin"] == "":
                blank[a.kind][0] += 1
            else:
                timelines[rec["isin"]].append((didx[a.date], rec["sym"], rec["ser"], a.kind,
                                                rec["ser"] in OVERLAY_SERIES, i))
            blank[a.kind][1] += 1
        per_file_rows[(a.kind, a.date)] = rows
    return dates, didx, timelines, per_file_rows, {k: {"blank_isin_rows": v[0], "rows": v[1]} for k, v in sorted(blank.items())}


# ---------------------------------------------------------------- FIX-SYMBOL-HIST-01
def fx_symbol_hist(files, w, args):
    dates, _didx, timelines, _pfr, blank_stats = corpus_ledger(files)
    multi_sym = multi_ser = stable = same_day_multi = 0
    trans = []
    for isin in sorted(timelines):
        ev = sorted(timelines[isin], key=lambda t: (t[0], t[5]))
        syms = sorted({e[1] for e in ev})
        base = [e for e in ev if not e[4]]
        base_sers = sorted({e[2] for e in base})
        has_overlay = any(e[4] for e in ev)
        by_day = defaultdict(set)
        for e in ev:
            by_day[e[0]].add(e[2])
        same = sum(1 for v in by_day.values() if len(v) > 1)
        same_day_multi += same
        if len(syms) > 1:
            multi_sym += 1
        if len(base_sers) > 1:
            multi_ser += 1
        if len(syms) == 1 and len(base_sers) == 1 and not has_overlay and same == 0:
            stable += 1
            continue
        prev = None
        for e in base:
            if prev is not None and (e[1] != prev[1] or e[2] != prev[2]):
                trans.append([isin, dates[prev[0]], prev[1], prev[2], dates[e[0]], e[1], e[2],
                              e[0] - prev[0], 1 if (e[1] != prev[1] and e[2] != prev[2]) else 0,
                              "SAME_DAY_COEXIST" if e[0] == prev[0] else "SEQUENCE"])
            prev = e
    w.json("FIX-SYMBOL-HIST-01", "summary.json", {
        "distinct_tracked_isins": len(timelines),
        "isins_with_multiple_symbols": multi_sym,
        "isins_with_multiple_base_series": multi_ser,
        "fully_stable_isins_summarized_not_listed": stable,
        "isins_with_same_day_multi_series_rows": same_day_multi,
        "blank_isin_stats_by_format": blank_stats,
        "method": "timelines keyed by non-blank ISIN; overlay rows tracked but excluded from transition "
                  "chain (they inform FIX-OVERLAY-SEM-01)",
    })
    w.csv("FIX-SYMBOL-HIST-01", "transitions.csv",
          ["isin", "last_old_date", "symbol_before", "series_before", "first_new_date", "symbol_after",
           "series_after", "gap_trading_days", "simultaneous_symbol_and_series_change", "transition_type"],
          sorted(trans, key=lambda r: (r[0], r[1], r[4])))


# ---------------------------------------------------------------- FIX-SERIES-EVENTS-01
def fx_series_events(files, w, args):
    dates, _didx, timelines, _pfr, _blank = corpus_ledger(files)
    pair_counts, cooc, focus = defaultdict(int), defaultdict(int), []
    st_kind = defaultdict(int)
    for isin in sorted(timelines):
        ev = sorted(timelines[isin], key=lambda t: (t[0], t[5]))
        prev = None
        by_day = defaultdict(set)
        day_kind = defaultdict(set)
        for e in ev:
            by_day[e[0]].add(e[2])
            day_kind[e[0]].add(e[3])
        for d, sers in by_day.items():
            if len(sers) > 1:
                kinds = day_kind[d]
                for a1 in sorted(sers):
                    for a2 in sorted(sers):
                        if a1 < a2:
                            cooc[(a1, a2)] += 1
                            if "ST" in (a1, a2):
                                for k in sorted(kinds):
                                    st_kind[k] += 1
        base = [e for e in ev if not e[4]]
        for prev, cur in zip(base, base[1:]):
            if prev[2] == cur[2] or prev[0] == cur[0]:
                continue
            pair_counts[(prev[2], cur[2])] += 1
            if prev[2] in FOCUS_SERIES or cur[2] in FOCUS_SERIES:
                focus.append([isin, prev[2], cur[2], dates[prev[0]], dates[cur[0]], prev[1], cur[1]])
    w.csv("FIX-SERIES-EVENTS-01", "transition_pair_counts.csv", ["transition", "count"],
          [["%s->%s" % k, v] for k, v in sorted(pair_counts.items())])
    w.csv("FIX-SERIES-EVENTS-01", "same_day_series_cooccurrence.csv", ["series_a", "series_b", "isin_days"],
          [[a, b, v] for (a, b), v in sorted(cooc.items())])
    w.csv("FIX-SERIES-EVENTS-01", "focus_transitions.csv",
          ["isin", "old_series", "new_series", "last_old_date", "first_new_date", "symbol_before", "symbol_after"],
          sorted(focus, key=lambda r: (r[3], r[0])))
    st_pairs = sorted([[a, b, v] for (a, b), v in cooc.items() if "ST" in (a, b)], key=lambda r: (-r[2], r[0], r[1]))[:20]
    w.json("FIX-SERIES-EVENTS-01", "st_anomaly_test.json", {
        "hypothesis_under_test": ("D02 observed ST rows/day ≈16.9 (last 250 Legacy files) vs ≈124.7 (first 250 "
                                  "UDiFF files). Competing explanations: usage shift for surveillance T2T "
                                  "reporting; semantic re-purposing under UDiFF; organic SME growth. Row tests: "
                                  "(1) ST same-day co-occurrence with SM/SZ/EQ for the same ISIN, (2) ST ISIN "
                                  "appearance in other series before/after transition."),
        "st_same_day_cooccurrence_by_format": dict(sorted(st_kind.items())),
        "top_ST_cooccurrence_pairs": st_pairs,
        "interpretation_owner": "D03 record; this fixture emits evidence only.",
    })


# ---------------------------------------------------------------- FIX-OVERLAY-SEM-01
def fx_overlay_sem(files, w, args):
    _dates, _didx, _tl, per_file_rows, _blank = corpus_ledger(files)
    detail, agg = [], defaultdict(int)
    for (kind, date), rows in sorted(per_file_rows.items()):
        by_isin, by_sym = defaultdict(list), defaultdict(list)
        for r in rows:
            if r["ser"] in OVERLAY_SERIES:
                continue
            if r["isin"]:
                by_isin[r["isin"]].append(r)
            by_sym[r["sym"]].append(r)
        for r in rows:
            if r["ser"] not in OVERLAY_SERIES:
                continue
            base, mt = None, "NO_BASE_ORPHAN"
            if r["isin"] and by_isin.get(r["isin"]):
                base, mt = by_isin[r["isin"]][0], "BASE_SAME_ISIN"
            elif r["sym"] and by_sym.get(r["sym"]):
                base, mt = by_sym[r["sym"]][0], "BASE_BY_SYMBOL_ONLY"
            agg["%s|%s|%s" % (kind, r["ser"], mt)] += 1
            rel = [""] * 6
            if base is not None:
                def cmpv(a, b):
                    fa, fb = fnum(a), fnum(b)
                    if fa is None or fb is None:
                        return "na"
                    return "eq" if fa == fb else ("lt" if fa < fb else "gt")
                rel = [cmpv(r["qty"], base["qty"]), cmpv(r["val"], base["val"]), cmpv(r["trd"], base["trd"]),
                       cmpv(r["close"], base["close"]),
                       "isin_eq" if (r["isin"] and r["isin"] == base["isin"]) else ("isin_blank" if not r["isin"] else "isin_ne"),
                       "base_series=" + base["ser"]]
            detail.append([kind, date, r["ser"], r["sym"], r["isin"], mt,
                           base["sym"] if base else "", base["ser"] if base else "", base["isin"] if base else ""]
                          + rel)
    w.csv("FIX-OVERLAY-SEM-01", "per_overlay_row.csv",
          ["format", "date", "overlay_series", "overlay_symbol", "overlay_isin", "match_type",
           "base_symbol", "base_series", "base_isin", "qty_rel", "val_rel", "trd_rel", "close_rel",
           "isin_cmp", "base_series_note"], sorted(detail))
    w.json("FIX-OVERLAY-SEM-01", "aggregate.json", {
        "counts_by_format_series_matchtype": dict(sorted(agg.items())),
        "reading_guidance": {
            "BASE_SAME_ISIN with isin_eq and qty_rel lt/eq": "consistent with overlay ⊂ or = base security record",
            "BASE_BY_SYMBOL_ONLY + overlay isin blank": "supports D02-Q1 reading (b): overlay rows carry no ISIN",
            "NO_BASE_ORPHAN": "overlay without same-day base — independent listing candidate; investigate",
        },
        "no_assumption": "This fixture does not classify overlays; it emits comparisons for both D02 readings.",
    })


# ---------------------------------------------------------------- FIX-ANOM-01
def fx_anom(files, w, args):
    dates = sorted({a.date for a in files})
    reports = []
    for t in ANOM_TARGETS:
        if t not in dates:
            w.json("FIX-ANOM-01", "missing_%s.json" % t, {"target": t, "status": "NOT FOUND in corpus"})
            continue
        i = dates.index(t)
        window = dates[max(0, i - 3):i + 4]
        per_date = {}
        for d in window:
            for a in [x for x in files if x.date == d]:
                names, _idx = header_index(a.path)
                raw = open(a.path, "rb").read()
                with zipfile.ZipFile(a.path) as zf:
                    inner = zf.namelist()[0]
                    data = zf.read(inner)
                    members = [{"name": n, "compress_type": zf.getinfo(n).compress_type,
                                "size": zf.getinfo(n).file_size,
                                "compress_size": zf.getinfo(n).compress_size,
                                "crc": zf.getinfo(n).CRC} for n in zf.namelist()]
                encs = {}
                for enc in ("ascii", "utf-8", "utf-8-sig", "cp1252"):
                    try:
                        data.decode(enc)
                        encs[enc] = "ok"
                    except Exception:
                        encs[enc] = "fail"
                text = data.decode("cp1252", errors="replace")
                crlf = text.count("\r\n")
                lf_only = text.count("\n") - crlf
                allr = list(csv.reader(io.StringIO(text)))
                field_hist, ts_hist = defaultdict(int), defaultdict(int)
                j = _idx.get("TIMESTAMP")
                for k, r in enumerate(allr):
                    field_hist[len(r)] += 1
                    if k and j is not None and j < len(r):
                        v = r[j].strip()
                        if re.fullmatch(r"\d{2}-[A-Z]{3}-\d{4}", v):
                            ts_hist["DD-MON-YYYY"] += 1
                        elif re.fullmatch(r"\d{2}-[A-Za-z]{3}-\d{2}", v):
                            ts_hist["DD-Mon-YY_2digit_year"] += 1
                        else:
                            ts_hist["OTHER"] += 1
                per_date[d] = {
                    "file": a.name, "kind": a.kind, "size_bytes": len(raw),
                    "sha256": hashlib.sha256(raw).hexdigest(), "zip_members": members,
                    "header_fields": len(names), "header": ",".join(names),
                    "field_count_hist": {str(k): v for k, v in sorted(field_hist.items())},
                    "timestamp_format_hist": dict(sorted(ts_hist.items())),
                    "encodings": encs, "bom_utf8": data[:3] == b"\xef\xbb\xbf",
                    "line_endings": {"crlf": crlf, "lf_only": lf_only},
                    "data_rows": max(len(allr) - 1, 0),
                    "first10": allr[1:11], "last10": allr[-10:] if len(allr) > 11 else [],
                }
        reports.append({"target": t, "window_dates": window, "per_file": per_date})
    w.json("FIX-ANOM-01", "report.json", {
        "targets": ANOM_TARGETS, "reports": reports,
        "external_copy_note": ("NSE-published-copy cross-check is left to the executor's network policy; "
                               "this tool performs NO network access. Local evidence is never replaced by an "
                               "external copy (D03 §12)."),
    })


# ---------------------------------------------------------------- orchestration
FIXTURES = {
    "FIX-SEM-DEF-01": fx_semdef,
    "FIX-UD-CENSUS-01": fx_ud_census,
    "FIX-UD-ROW-SAMPLE-01": fx_row_sample,
    "FIX-LEG-CENSUS-01": fx_leg_census,
    "FIX-XCONT-01": fx_xcont,
    "FIX-SYMBOL-HIST-01": fx_symbol_hist,
    "FIX-SERIES-EVENTS-01": fx_series_events,
    "FIX-OVERLAY-SEM-01": fx_overlay_sem,
    "FIX-ANOM-01": fx_anom,
}


def parse_args(argv):
    ap = argparse.ArgumentParser(description="D03 read-only fixture scan tool")
    ap.add_argument("--legacy-root", default=r"C:\IIPS_Data\NSE_Legacy_Acquisition\archives")
    ap.add_argument("--udiff-root", default=r"C:\IIPS_Data\NSE_CM_UDiFF_10Y\archives")
    ap.add_argument("--out", default="./d03_out")
    ap.add_argument("--d01-inventory", default="", help="path to committed evidence/inventory/file_inventory.json")
    ap.add_argument("--fixtures", default="all")
    ap.add_argument("--frozen-time", default="", help="fixed generation timestamp for determinism tests")
    ap.add_argument("mode", nargs="?", default="run", choices=["run", "verify"])
    return ap.parse_args(argv)


def generate(args, outdir):
    files = discover(args.legacy_root, args.udiff_root)
    if not files:
        raise SystemExit("no archives discovered — check roots")
    ids = list(FIXTURES) if args.fixtures == "all" else [x.strip() for x in args.fixtures.split(",")]
    for i in ids:
        if i not in FIXTURES:
            raise SystemExit("unknown fixture " + i)
    os.makedirs(outdir, exist_ok=True)
    w = Writer(outdir)
    for fid in ids:
        FIXTURES[fid](files, w, args)
    payload = sorted(os.path.basename(p) for p in w.payloads if not p.endswith("RUN_INFO.json"))
    runinfo = {
        "tool_version": TOOL_VERSION,
        "tool_sha256": sha256_file(os.path.abspath(__file__)),
        "generated_utc": args.frozen_time or _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"),
        "fixtures": ids,
        "roots": {"legacy": args.legacy_root, "udiff": args.udiff_root},
        "files_by_kind": {k: sum(1 for f in files if f.kind == k) for k in ("LEGACY", "UDIFF")},
        "read_only": True,
        "determinism": {"rng": "none", "sort_keys": "explicit primary+secondary", "frozen_time": args.frozen_time or "(live clock)"},
        "selection_criteria": {
            "sem_def_targets": ["%s|%s" % t for t in SEMDEF_TARGETS],
            "row_sample_udiff": ROW_SAMPLE_UDIFF + ["+dynamic: max-BL date, first TradDt!=BizDt date"],
            "row_sample_legacy": ROW_SAMPLE_LEGACY,
            "anomaly_targets": ANOM_TARGETS,
            "row_sample_rule": "first 25 rows per series class in file order; +up to 200 special rows (RE*/ETF-hint/blank-ISIN/blank-FinInstrmId); merge; sort by original row index; cap <=2000/date",
            "file_selection_rule": "exact date, else earliest on/after target (tie by name)",
        },
        "payload_files": payload,
    }
    with open(os.path.join(outdir, "RUN_INFO.json"), "w", encoding="utf-8") as f:
        json.dump(runinfo, f, indent=2, sort_keys=True)
        f.write("\n")
    with open(os.path.join(outdir, "MANIFEST.sha256"), "w", encoding="utf-8") as f:
        for name in payload:
            f.write("%s  %s\n" % (sha256_file(os.path.join(outdir, name)), name))
    return runinfo


def main(argv=None):
    args = parse_args(argv)
    if args.mode == "verify":
        bad = 0
        with open(os.path.join(args.out, "MANIFEST.sha256")) as f:
            for line in f:
                h, n = line.split(None, 1)
                if sha256_file(os.path.join(args.out, n.strip())) != h:
                    print("HASH MISMATCH:", n)
                    bad += 1
        print("verify: " + ("OK" if bad == 0 else "%d MISMATCHES" % bad))
        return 1 if bad else 0
    generate(args, args.out)
    print("D03 fixtures generated under " + args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
